// Generated by CoffeeScript 1.6.3
(function() {
  define(["backbone", "models/Todo", "localStorage"], function(Backbone, Todo) {
    "use strict";
    var isCompleted;
    isCompleted = function(todo) {
      return todo.get("completed");
    };
    return Backbone.Collection.extend({
      model: Todo,
      localStorage: new Backbone.LocalStorage("todos-backbone"),
      getCompleted: function() {
        return this.filter(isCompleted);
      },
      getActive: function() {
        return this.reject(isCompleted);
      },
      comparator: function(todo) {
        return todo.get("created");
      }
    });
  });

}).call(this);
