// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["marionette", "jquery"], function(Marionette, $) {
    var ActiveCountView, _ref;
    return ActiveCountView = (function(_super) {
      __extends(ActiveCountView, _super);

      function ActiveCountView() {
        _ref = ActiveCountView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ActiveCountView.prototype.initialize = function() {
        return this.listenTo(this.collection, "all", this.render);
      };

      ActiveCountView.prototype.render = function() {
        var itemsLeft, itemsWord;
        this.$el = $("#todo-count");
        itemsLeft = this.collection.getActive().length;
        itemsWord = itemsLeft < 1 || itemsLeft > 1 ? "items" : "item";
        return this.$el.html("<strong>" + itemsLeft + "</strong>" + itemsWord + " left");
      };

      return ActiveCountView;

    })(Marionette.View);
  });

}).call(this);
