// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["marionette", "jquery"], function(Marionette, $) {
    var CompletedCountView, _ref;
    return CompletedCountView = (function(_super) {
      __extends(CompletedCountView, _super);

      function CompletedCountView() {
        _ref = CompletedCountView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      CompletedCountView.prototype.initialize = function() {
        return this.listenTo(this.collection, "all", this.render);
      };

      CompletedCountView.prototype.render = function() {
        var completedTodos;
        this.$el = $("#clear-completed");
        completedTodos = this.collection.getCompleted();
        return this.$el.toggle(completedTodos.length).html("Clear completed(" + completedTodos.length + ")");
      };

      return CompletedCountView;

    })(Marionette.View);
  });

}).call(this);
