// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['marionette', 'templates', 'views/ActiveCountView', 'views/CompletedCountView'], function(Marionette, templates, ActiveCountView, CompletedCountView) {
    var FooterView, _ref;
    return FooterView = (function(_super) {
      __extends(FooterView, _super);

      function FooterView() {
        _ref = FooterView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      FooterView.prototype.template = templates.footer;

      FooterView.prototype.regions = {
        activeCount: "#todo-count",
        completedCount: "#clear-completed"
      };

      FooterView.prototype.ui = {
        filters: "#filters a"
      };

      FooterView.prototype.events = {
        "click #clear-completed": "onClearClick"
      };

      FooterView.prototype.onRender = function() {
        this.activeCount.show(new ActiveCountView({
          collection: this.collection
        }));
        return this.completedCount.show(new CompletedCountView({
          collection: this.collection
        }));
      };

      FooterView.prototype.updateFilterSelection = function(filter) {
        return this.ui.filters.removeClass("selected").filter("[href='#/" + filter + "']").addClass("selected");
      };

      FooterView.prototype.onClearClick = function() {
        return window.app.vent.trigger("todoList:clear:completed");
      };

      return FooterView;

    })(Marionette.Layout);
  });

}).call(this);
