// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "localStorage"], function(Backbone) {
    "use strict";
    var Todo, _ref;
    return Todo = (function(_super) {
      __extends(Todo, _super);

      function Todo() {
        _ref = Todo.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Todo.prototype.localStorage = new Backbone.LocalStorage("todos-backbone");

      Todo.prototype.defaults = {
        title: "",
        completed: false,
        created: 0
      };

      Todo.prototype.initialize = function() {
        if (this.isNew()) {
          return this.set("created", Date.now());
        }
      };

      Todo.prototype.toggle = function() {
        return this.set("completed", !this.get("completed"));
      };

      return Todo;

    })(Backbone.Model);
  });

}).call(this);
