// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TodoMVC.module("Todos", function(Todos, App, Backbone, Marionette, $, _) {
    var localStorageKey, _ref, _ref1;
    localStorageKey = "todos-backbone-marionettejs";
    Todos.Todo = (function(_super) {
      __extends(Todo, _super);

      function Todo() {
        _ref = Todo.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Todo.prototype.localStorage = new Backbone.LocalStorage(localStorageKey);

      Todo.prototype.defaults = {
        title: "",
        completed: false,
        created: 0
      };

      Todo.prototype.initialize = function() {
        if (this.isNew()) {
          return this.set("created", Date.now());
        }
      };

      Todo.prototype.toggle = function() {
        return this.set("completed", !this.isCompleted());
      };

      Todo.prototype.isCompleted = function() {
        return this.get("completed");
      };

      return Todo;

    })(Backbone.Model);
    return Todos.TodoList = (function(_super) {
      __extends(TodoList, _super);

      function TodoList() {
        _ref1 = TodoList.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      TodoList.prototype.model = Todos.Todo;

      TodoList.prototype.localStorage = new Backbone.LocalStorage(localStorageKey);

      TodoList.prototype.getCompleted = function() {
        return this.filter(this._isCompleted);
      };

      TodoList.prototype.getActive = function() {
        return this.reject(this._isCompleted);
      };

      TodoList.prototype.comparator = function(todo) {
        return todo.get("created");
      };

      TodoList.prototype._isCompleted = function(todo) {
        return todo.isCompleted();
      };

      return TodoList;

    })(Backbone.Collection);
  });

}).call(this);
