// Generated by CoffeeScript 1.6.3
(function() {
  var TodoMVC,
    _this = this;

  this.TodoMVC = TodoMVC = new Backbone.Marionette.Application();

  TodoMVC.addRegions({
    header: "#header",
    main: "#main",
    footer: "#footer"
  });

  TodoMVC.on("initialize:after", function() {
    return Backbone.history.start();
  });

}).call(this);
