// Generated by CoffeeScript 1.6.3
(function() {
  define(["app"], function(app) {
    "use strict";
    return {
      setFilter: function(param) {
        return app.vent.trigger("todoList:filter", param && param.trim() || "");
      }
    };
  });

}).call(this);
